// app/layout.tsx
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/layout/Footer";

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // Added 700 for bold text
  variable: "--font-body",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Future Axis",
  description: "Generated by create next app",
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html
          lang="en"
          className={`${inter.variable} h-full antialiased`}
      >
        <body className="min-h-full flex flex-col font-sans" style={{ fontFamily: "var(--font-body)" }}>
          <main className="flex-1">
            {children}
          </main>
          <Footer />
        </body>
      </html>
  );
}